# fly.toml file generated for hombrew-turbo-test on 2023-04-01T23:32:48-03:00

app = "hombrew-turbo-test"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "scl"

[env]
  CMS_URL = "http://127.0.0.1:1337"
  STRAPI_HOST = "0.0.0.0"
  STRAPI_PORT = 1337

[mounts]
  destination = "/data"
  processes = ["admin"]
  source = "hombrewturbotestdata"

[processes]
  admin = "pnpm start --filter=admin"
  web = "pnpm start --filter=web"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["web"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "10s"
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
